In [25]:
import pandas as pd
import numpy as np
import os
import sys
import pulp

data = pd.read_csv('../data/responses.csv')
# Drop the first row if it is a test
data["Full name"] = data["First name"] + " " + data["Last name"]
data.drop([0], inplace=True)
data.drop_duplicates(subset = ["Full name"], inplace = True)
data.head(5)

,Timestamp,First name,Last name,Email,Mobile number,Student Username/UPI,Dietary Requirements?,Name one person who you would like to be in a team with? (N/A if nobody),"Are you a 2025 KAC member (if you're returning but not yet signed up, answer ""No"")?",KAC card number?,Please Upload a Screenshot of Your Payment,Preference,"In signing up to this event, I consent to appearing in any photos/videos taken by KAC for social media purposes.",Full name
1,5/18/2025 18:01:58,Isaac,Ngai,isaacngai2005@gmail.com,02102850729,inga710,no,rosanne,Yes,0648,https://drive.google.com/open?id=1IOmh0pXrsIwx...,Rosanne,YES,Isaac Ngai
2,5/18/2025 18:02:02,Kayde,Huang,Kayde.huang@gmail.com,0279170506,NA (AUT),NaN,NaN,Yes,144,https://drive.google.com/open?id=1FWW8w-V5GQpp...,NaN,YES,Kayde Huang
3,5/18/2025 18:02:04,andrea,ramos,eycie.ramos@gmail.com,021445220,NaN,none,Isaac and Rosanell,Yes,NaN,https://drive.google.com/open?id=14FHLy_D6G2tE...,"Isaac, Rosanne",YES,andrea ramos
4,5/18/2025 18:02:15,Rosanne,Lai,rosannelai1127@gmail.com,0211306760,llai228,no,Isaac,Yes,1159,https://drive.google.com/open?id=1wQnvnFfng1Y_...,Isaac,YES,Rosanne Lai
5,5/18/2025 18:02:17,Marcus,Fuller,marcusdsfuller@gmail.com,0224060454,mful720,na,Melody,Yes,1200,https://drive.google.com/open?id=1QUKTzcbWv9NQ...,Melody,YES,Marcus Fuller

In [27]:
data[["First name", "Last name", "Full name", "Preference"]]

,First name,Last name,Full name,Preference
1,Isaac,Ngai,Isaac Ngai,Rosanne
2,Kayde,Huang,Kayde Huang,NaN
3,andrea,ramos,andrea ramos,"Isaac, Rosanne"
4,Rosanne,Lai,Rosanne Lai,Isaac
5,Marcus,Fuller,Marcus Fuller,Melody
6,Andrew,Kim,Andrew Kim,Stas
7,Stas,Tigay,Stas Tigay,Andrew Kim😍
8,Artur,Rakhimov,Artur Rakhimov,NaN
9,Luca,Lin,Luca Lin,NaN
10,matthew,chen,matthew chen,NaN
11,Ethan,Wongso,Ethan Wongso,NaN
12,Chanul,Jayasekera,Chanul Jayasekera,Victor Tran
13,Miu,Vong,Miu Vong,grace joyce
14,Amelia,Yamaguchi,Amelia Yamaguchi,Chinny
15,Melody,Bedggood,Melody Bedggood,marcus fuller
16,Daniel,Cha,Daniel Cha,NaN
17,Sophie,Lee Sang,Sophie Lee Sang,Halle Tang
18,Dora,Zhou,Dora Zhou,Kate zhu
19,Edmond,Liu,Edmond Liu,NaN
20,Killian,Zhao,Killian Zhao,"jason xie, melody bedggood, reya rawat"
21,Disala,Bandara,Disala Bandara,Lauren Xu
22,Halle,Tang,Halle Tang,Sophie Lee Sang
23,Khiem,Pham,Khiem Pham,Hernan Cortez Moreno
24,Rebecca,Eda,Rebecca Eda,Edmond
25,Zee,Affandi,Zee Affandi,NaN
26,Prince,De Los Santos,Prince De Los Santos,Ryan Chen
27,Kate,Zhu,Kate Zhu,Dora zhou
28,Stephen,Fan,Stephen Fan,Jin
29,Lauren,Xu,Lauren Xu,Disala
30,Justin,Carigo,Justin Carigo,NaN
31,Hernan,Cortes,Hernan Cortes,Khiem Pham
32,Jason,Xie,Jason Xie,"Killian, Reya"
33,Reya,Rawat,Reya Rawat,Jason Xie
34,Edward,Xu,Edward Xu,NaN
35,Chinny,Quilbio,Chinny Quilbio,Amelia
36,Adam,Yu,Adam Yu,"orlando, jack"
37,Haydn,Chau,Haydn Chau,"Allie chan, isaac ngai"
38,Ryan,Chen,Ryan Chen,Prince de los Santos
39,Allie,Chan,Allie Chan,Haydn Chau
40,Miranda,Zhang,Miranda Zhang,Holly
41,Holly,Gao,Holly Gao,Miranda Zhang
42,Ganesh,Mahesh,Ganesh Mahesh,NaN
43,Rex,Yong,Rex Yong,NaN
44,Melvin,Jia,Melvin Jia,NaN
45,Evonne,Teng,Evonne Teng,Ruth Xu
46,raphael,dimaun,raphael dimaun,ricky
47,Ricky,Fernandez,Ricky Fernandez,Raph Dimuan
48,Angelina,Djaja,Angelina Djaja,Fiona Yang

In [31]:
data["Preference"].apply(lambda x: str(x).split(",").strip()str[0])

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2108812681.py, line 1)